version: "3"
services:
  auth_psql:
    image: postgres:latest
    ports:
      - "${AUTH_PSQL_PORT}:${AUTH_PSQL_PORT}"
    environment:
      - POSTGRES_USER=${AUTH_PSQL_USER}
      - POSTGRES_PASSWORD=${AUTH_PSQL_PASSWORD}
      - POSTGRES_DB=${AUTH_PSQL_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - microservices

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices

volumes:
  pg_data:
    driver: local
  rabbit_data:
    driver: local

networks:
  microservices:
    driver: bridge
